import { pdfRefs } from './pdfRefs'
import type { SessionDefinition } from './types'

export const sessionDefinitions: SessionDefinition[] = [
  {
    id: 'kw25-di-2026-06-16',
    date: '2026-06-16',
    kw: 'KW25',
    title: 'Dienstag 16. Juni: Onboarding + Bewegung',
    type: 'training',
    summary:
      'Kennenlernen, Ampel setzen, Schmerzen/Returner grob erfassen, Bewegung beobachten und leicht trainieren. Kein Testtag.',
    primarySource: 'plans/offseason_coach_sheets/KW25_tuesday_training_plan_clear_2026-06-16.md',
    pdfRefs: [pdfRefs.kw25TuesdayPlan, pdfRefs.kw25TuesdayCoachScript, pdfRefs.coachCardTuesday],
    goals: [
      'Kennenlernen und Trainingskultur setzen',
      'Ampel, Schmerz, Life-Flag und Returnerstatus grob erfassen',
      'Bewegung beobachten und leicht trainieren',
      'Kein Ranking, kein Bronco, kein 30-m-Test',
    ],
    timeline: [
      {
        time: '0-8',
        title: 'Ankommen',
        work: 'Namen sammeln, Blatt starten, Einwilligung falls noetig.',
        dose: 'ruhig',
        note: 'Name eintragen',
      },
      {
        time: '8-14',
        title: 'Teamansage',
        work: 'Ziel, Ampel und ehrliche Rueckmeldung erklaeren.',
        dose: '60 Sekunden',
        note: 'Testdruck rausnehmen',
      },
      {
        time: '14-24',
        title: 'Kurzcheck',
        work: 'Position, Readiness, Schmerz + Ort, Life-Flag und Returnerstatus.',
        dose: 'pro Spieler kurz',
        note: 'Ampel setzen',
      },
      {
        time: '24-36',
        title: 'Warm-up',
        work: 'Lauf 1x20 m, rueckwaerts 1x20 m, Shuffle 1x20 m/Seite, A-March, Dribble, Pogo, Snap-down.',
        dose: 'RPE 2-3',
        note: 'Laufbild und Schmerz beobachten',
      },
      {
        time: '36-46',
        title: 'Movement Check',
        work: 'Adductor Squeeze, Ankle/Calf, Push-up Plus/Incline, Single-leg Bridge, Self-Neck-ISO nur symptomfrei.',
        dose: 'nur beobachten',
        note: 'nur Auffaelliges notieren',
      },
      {
        time: '46-58',
        title: 'Technik 1',
        work: 'Squat, Hinge, Push, Row und Carry.',
        dose: '2 Runden, RPE 4-5',
        note: 'Technikstandard setzen',
      },
      {
        time: '58-68',
        title: 'Speed Prep',
        work: '3x15 m bei 60/70/80 Prozent, optional 2x20 m nur Gruen.',
        dose: '60-90 s Gehpause',
        note: 'kein Timing',
      },
      {
        time: '68-80',
        title: 'Technik 2',
        work: 'Split Squat, DB/KB DL, MB Chest Pass technisch, Band ER, Dead Bug.',
        dose: '1-2 Runden, RPE 4-5',
        note: 'keine Weiten messen',
      },
      {
        time: '80-86',
        title: 'Lockerer Abschluss',
        work: '4x40 m locker nur Gruen oder Mobility.',
        dose: '60-70 Prozent',
        note: 'optional',
      },
      {
        time: '86-90',
        title: 'Abschluss',
        work: 'sRPE 0-10, Schmerz nach Einheit, Donnerstag-Entscheidung.',
        note: 'sRPE, Pain, E2',
      },
    ],
    materials: ['Klemmbrett', 'Check-in-Blatt', 'Huetchen', 'DB/KB', 'Med-Ball', 'Baender', 'Carry-Flaeche'],
    safetyNotes: [
      'Dienstag ist kein Testtag und kein Ranking.',
      'Gelb: 30-50 Prozent weniger, kein harter Sprint, keine Zusatzkondition.',
      'Rot: kein normales Training; Kopf/Nacken/Concussion/neurologisch medizinisch klaeren.',
      'Keine Diagnosen aufschreiben.',
    ],
    coachNotes: [
      'Bei Zeitdruck zuerst lockeren Abschluss streichen.',
      'Bei grosser oder chaotischer Gruppe keine optionalen 20 m und keinen lockeren Abschluss.',
      'Nachher Gelb/Rot, Returner/offen und Donnerstag-Entscheidung markieren.',
    ],
    libraryRefs: ['coach-script-kw25', 'spieler-briefing-start', 'detail-briefing-unit-1', 'variants-abcd'],
  },
  {
    id: 'kw25-do-2026-06-18',
    date: '2026-06-18',
    kw: 'KW25',
    title: 'Donnerstag 18. Juni: Training + Mini-Baseline optional',
    type: 'baseline',
    summary:
      'Reaktion auf Dienstag pruefen, Grundmuster sauber trainieren und optional zwei einfache Startwerte sammeln, nur wenn die Gruppe ruhig ist.',
    primarySource: 'plans/offseason_coach_sheets/KW25_thursday_training_plan_clear_2026-06-18.md',
    pdfRefs: [
      pdfRefs.kw25ThursdayPlan,
      pdfRefs.kw25ThursdayDeepPlaybook,
      pdfRefs.thursdayCompact,
    ],
    goals: [
      'Reaktion auf Dienstag pruefen',
      'Grundmuster sauber trainieren',
      'Optional Broad Jump und Med-Ball Chest Pass erfassen',
      'Kein 30-m-Test und kein Bronco',
    ],
    timeline: [
      {
        time: '0-8',
        title: 'Check-in',
        work: 'Ampel, Reaktion auf Dienstag, neue Schmerzen und Returner-Limit.',
        note: 'Ampel, Schmerz, Ret',
      },
      {
        time: '8-18',
        title: 'Warm-up',
        work: 'Lauf 2x20 m, Shuffle, A-March, Dribble, Pogo, Snap-down.',
        dose: 'RPE 2-3',
        note: 'Laufbild',
      },
      {
        time: '18-28',
        title: 'Speed',
        work: '4x10 m plus optional 2x15 m.',
        dose: '70-80 Prozent, 60-90 s Gehpause',
        note: 'kein Timing',
      },
      {
        time: '28-40',
        title: 'Mini-Baseline optional',
        work: 'Broad Jump 2 Versuche und MB Chest Pass 2 Versuche.',
        dose: 'nur wenn ruhig',
        note: 'kein Ranking',
      },
      {
        time: '40-64',
        title: 'Kraft Pods',
        work: 'Squat, Hinge, Push/Pull und Carry.',
        dose: 'RPE 5-6, 45-75 s Wechselpause',
        note: 'Technik/Last grob',
      },
      {
        time: '64-74',
        title: 'Microdose',
        work: 'Adductor Squeeze, Calf Raise, Band ER, Dead Bug oder Side Plank, Self-Neck-ISO nur symptomfrei.',
        dose: 'schmerzfrei',
        note: 'Problem ja/nein',
      },
      {
        time: '74-84',
        title: 'Easy Tempo',
        work: '6x40-60 m locker oder 6-8 min Bike/Erg.',
        dose: '60-70 Prozent, sprechen koennen',
        note: 'nur wenn gemacht',
      },
      {
        time: '84-90',
        title: 'Abschluss',
        work: 'sRPE, Pain/Issue und KW26-Hinweis.',
        note: 'sRPE, Pain',
      },
    ],
    materials: ['Huetchen', 'DB/KB', 'Med-Ball', 'Baender', 'Carry-Flaeche', 'Bike/Erg optional'],
    safetyNotes: [
      'Mini-Baseline nur wenn ruhig, sicher und genug Platz vorhanden ist.',
      'Spieler nicht ranken; Vergleich ist spaeter mit sich selbst.',
      'Bei vielen Gelb/Rot: keine Mini-Baseline, Speed reduzieren, kein Easy Tempo.',
      '30 m und Bronco bleiben nicht aktiv verpflichtend.',
    ],
    coachNotes: [
      'Bei Zeitdruck zuerst Easy Tempo streichen, dann Mini-Baseline.',
      'Bei Regen/rutschigem Feld keine Jumps/Speed, stattdessen Bike/Erg oder Technikpods.',
      'Wenn keine Werte entstehen, nichts nachholen erzwingen.',
    ],
    libraryRefs: [
      'deep-playbook-donnerstag-kw25',
      'coach-script-kw25',
      'variants-abcd',
      'exercise-mapping-offseason',
    ],
  },
  {
    id: 'kw26-di-2026-06-23',
    date: '2026-06-23',
    kw: 'KW26',
    title: 'Dienstag 23. Juni: Session 1A',
    type: 'training',
    summary: 'Routine, Beschleunigung und Krafttechnik. Ziel-RPE 6.',
    primarySource: 'plans/offseason_coach_sheets/kw25_27_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw25To27Cards, pdfRefs.exerciseMapping],
    goals: ['Routine aufbauen', 'Beschleunigung dosieren', 'Krafttechnik stabilisieren'],
    timeline: [
      { time: '0-17', title: 'Check-in + Prep', work: 'Ampel, Schmerz, Returner; RAMP, Sprintmechanik, Pogo, Snap-down, Plant-hold.' },
      { time: '17-38', title: 'Speed + Power', work: '4x10 m + 3x15 m; Broad Jump/CMJ + Stick, MB Chest Pass.' },
      { time: '38-74', title: 'Kraft Pods + Microdose', work: 'Goblet/Box Squat, DB Floor Press/Row, Split Squat/Carry; Assisted Nordic und Adductor Squeeze.' },
      { time: '74-90', title: 'Tempo + Abschluss', work: '6x60 m extensive, sRPE, Pain/Issue, Techniknotiz.' },
    ],
    materials: ['Huetchen', 'MB', 'DB/KB', 'Baender', 'Carry-Flaeche', 'Trap Bar optional'],
    safetyNotes: ['Y = weniger Reps, kein Extra-Tempo.', 'Keine Rennen gegeneinander.'],
    coachNotes: ['CF Carry schwerer; HY Split Squat/Plant priorisieren; SB nur Gruen mit 1-2 Build-ups.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw26-do-2026-06-25',
    date: '2026-06-25',
    kw: 'KW26',
    title: 'Donnerstag 25. Juni: Session 1B',
    type: 'training',
    summary: 'Zweiter Ganzkoerperreiz ohne hohe Ermuedung; Landen, Bremsen und Power. RPE 5-6.',
    primarySource: 'plans/offseason_coach_sheets/kw25_27_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw25To27Cards, pdfRefs.exerciseMapping],
    goals: ['Qualitaet halten', 'Landen/Bremsen vorbereiten', 'Bronco nicht noetig'],
    timeline: [
      { time: '0-24', title: 'Check-in + Prep + Speed', work: 'Ampel, Muskelkater, kurze RAMP, Pogo, Dribble, Snap-down, 3-4x20 m smooth fast.' },
      { time: '24-58', title: 'Power + Kraft', work: 'MB Scoop, Low Box/Squat Jump, KB/Trap Bar DL, Push/Pull, Step-up/Reverse Lunge.' },
      { time: '58-90', title: 'Robustheit + Conditioning', work: 'Calf, Band ER, Side Plank, lockere Tempo Runs oder Bike/Erg, Abschluss.' },
    ],
    materials: ['MB', 'Box optional', 'KB/Trap Bar', 'Baender', 'Bike/Erg optional'],
    safetyNotes: ['Bei starker Dienstag-Reaktion kuerzen.', 'Bronco in KW26 nicht noetig.'],
    coachNotes: ['Kein Finisher; Conditioning bleibt locker-moderat.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw27-di-2026-06-30',
    date: '2026-06-30',
    kw: 'KW27',
    title: 'Dienstag 30. Juni: Session 2A',
    type: 'training',
    summary: 'Beschleunigung stabilisieren, Kraftumfang leicht steigern, erste Cluster-Farbe. RPE 6-7.',
    primarySource: 'plans/offseason_coach_sheets/kw25_27_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw25To27Cards, pdfRefs.exerciseMapping],
    goals: ['Accel-Qualitaet', 'Kraftumfang leicht steigern', 'ein Cluster-Fokus'],
    timeline: [
      { time: '0-29', title: 'Check-in + Prep + Speed', work: 'Ampel, Returner, Schmerz; A-Skip, Line Hops, Snap-down, Starts und 15-20 m.' },
      { time: '29-65', title: 'Power + Kraft Pods', work: 'Broad Jump, MB Punch/Chest, Trap Bar/Squat, Push/Pull, RFESS/Split Squat, Carry.' },
      { time: '65-90', title: 'Cluster + Microdose + Conditioning', work: 'CF Sled, HY Decel, SB Build-up; Nordic/Copenhagen; 2 Serien Intervall.' },
    ],
    materials: ['Huetchen', 'MB', 'Trap Bar/DB', 'Sled optional', 'Baender'],
    safetyNotes: ['Y: 1 Conditioning-Serie oder streichen.', 'Returner offen: kein Cluster-Speed/COD.'],
    coachNotes: ['Keine Nachholbelastung fuer verpasste Einheiten.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw27-do-2026-07-02',
    date: '2026-07-02',
    kw: 'KW27',
    title: 'Donnerstag 2. Juli: Session 2B',
    type: 'training',
    summary: 'Power und Max-V-Annaeherung dosieren, Kraftsignal erhalten, nicht ermueden. RPE 5-6.',
    primarySource: 'plans/offseason_coach_sheets/kw25_27_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw25To27Cards, pdfRefs.exerciseMapping],
    goals: ['frisch bleiben', 'Speed dosieren', 'Kraftsignal erhalten'],
    timeline: [
      { time: '0-25', title: 'Check-in + Prep + Speed', work: 'Ampel/Muskelkater, kurze RAMP, Dribble, Pogo, Snap-down, clusterangepasste smooth reps.' },
      { time: '25-58', title: 'Power + Kraft', work: 'CMJ + Stick, MB Rotational/Scoop, Squat/Trap Bar, Pull/Row, DB Press/Push-up.' },
      { time: '58-90', title: 'Robustheit + Tempo', work: 'Calf/Soleus, Neck Iso, Dead Bug, 6-8x60-80 m Tempo, Abschluss.' },
    ],
    materials: ['MB', 'Trap Bar/DB', 'Pull-up/Row Setup', 'Baender', 'Tempo-Flaeche'],
    safetyNotes: ['Donnerstag nicht ermueden.', 'Nackenarbeit nur symptomfrei.'],
    coachNotes: ['Kuerzen: Kraft nur 2 Saetze, Tempo 6 Reps oder streichen.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw28-di-2026-07-07',
    date: '2026-07-07',
    kw: 'KW28',
    title: 'Dienstag 7. Juli: Session 3A',
    type: 'training',
    summary: 'Stabiler Arbeitsreiz, kontrollierte Kontaktvorbereitung ohne Full Contact, Kraftbasis. RPE 7 fuer Gruen.',
    primarySource: 'plans/offseason_coach_sheets/kw28_31_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw28To31Cards, pdfRefs.exerciseMapping],
    goals: ['Arbeitsreiz setzen', 'Contact Prep kontrolliert', 'Kraftbasis entwickeln'],
    timeline: [
      { time: '0-28', title: 'Check-in + Prep + Speed', work: 'Ampel, Returner, Contact-Status; RAMP, Plant, 10-20 m Speed, CF optional Sled March.' },
      { time: '28-64', title: 'Power + Kraft Pods', work: 'Broad Jump/DB Jump Squat, MB Chest/Scoop, Trap Bar/Squat, Press/Row, Split Squat/Carry.' },
      { time: '64-90', title: 'Contact Prep + Microdose + Conditioning', work: 'Brace ISO/Sled/Shield Connection, Nordic/Copenhagen/Band ER, Intervall nur bei stabiler Technik.' },
    ],
    materials: ['Huetchen', 'MB', 'Trap Bar/DB', 'Sled/Shield optional', 'Baender'],
    safetyNotes: ['No-Go: Live-Kontakt, offene Returner in Contact Prep, Kopf/Nackenflag ignorieren.'],
    coachNotes: ['Contact Prep kurz und kontrolliert halten.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw28-do-2026-07-09',
    date: '2026-07-09',
    kw: 'KW28',
    title: 'Donnerstag 9. Juli: Session 3B',
    type: 'training',
    summary: 'Konsolidieren, Qualitaet vor Dichte, Review vor Aufbauphase. RPE 5-6.',
    primarySource: 'plans/offseason_coach_sheets/kw28_31_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw28To31Cards, pdfRefs.exerciseMapping],
    goals: ['Qualitaet konsolidieren', 'Regelmaessigkeit reviewen', 'nicht ueberladen'],
    timeline: [
      { time: '0-25', title: 'Check-in + Prep + Speed', work: 'Wochenrueckmeldung, RAMP, Dribble, Neck/Shoulder, smooth fast 20-30 m.' },
      { time: '25-58', title: 'Power + Kraft', work: 'MB Throws, Low Box Jump/CMJ, Trap Bar/Squat, Row, Carry.' },
      { time: '58-90', title: 'Robustheit + Conditioning + Review', work: 'Calf/Soleus, Side Plank, Adductor, 8-10 min Tempo, Notizen fuer KW29.' },
    ],
    materials: ['MB', 'Box optional', 'Trap Bar/DB', 'Baender', 'Tempo-Flaeche'],
    safetyNotes: ['Default kein harter Test.', 'Conditioning bei Bedarf streichen.'],
    coachNotes: ['Review: Wer ist regelmaessig da, wer bleibt Y/Returner, passen Cluster?'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw29-di-2026-07-14',
    date: '2026-07-14',
    kw: 'KW29',
    title: 'Dienstag 14. Juli: Session 4A',
    type: 'training',
    summary: 'Kraft/Power progressiv steigern, Cluster deutlicher. RPE 7, stabile Gruene kurz 7-8.',
    primarySource: 'plans/offseason_coach_sheets/kw28_31_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw28To31Cards, pdfRefs.exerciseMapping],
    goals: ['Kraft/Power progressiv steigern', 'Cluster deutlicher nutzen', 'Life Load beachten'],
    timeline: [
      { time: '0-28', title: 'Check-in + Prep + Speed', work: 'Ampel und letzte 7 Tage Belastung, Sprintmechanik, Pogo, Decel Stick, 10-20 m Speed.' },
      { time: '28-65', title: 'Power + Kraft Pods', work: 'DB Jump Squat/Broad Jump, MB Punch/Scoop, Trap Bar/Squat 4x4, Press/Row, RFESS/Carry.' },
      { time: '65-90', title: 'Cluster + Microdose + Conditioning', work: 'CF Sled/Brace, HY Accel-Decel-Reaccel, SB Fly-in dosiert, Nordic/Copenhagen, 3 Serien Intervall.' },
    ],
    materials: ['Huetchen', 'MB', 'Trap Bar/DB', 'Sled optional', 'Baender'],
    safetyNotes: ['Stop bei schlechter Technik, zu hohem RPE oder steigendem Schmerz.'],
    coachNotes: ['Kein Grind; stabile Gruene duerfen nur kontrolliert progressieren.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw29-do-2026-07-16',
    date: '2026-07-16',
    kw: 'KW29',
    title: 'Donnerstag 16. Juli: Session 4B',
    type: 'training',
    summary: 'Sprintqualitaet und Power, Kraft erhalten, nicht zerstoeren. RPE 5-6.',
    primarySource: 'plans/offseason_coach_sheets/kw28_31_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw28To31Cards, pdfRefs.exerciseMapping],
    goals: ['Sprintqualitaet', 'Power klein dosieren', 'Kraft technisch erhalten'],
    timeline: [
      { time: '0-25', title: 'Check-in + Prep + Speed', work: 'Ampel, schwere Beine beachten, kurze RAMP, clusterangepasste Speed-Reps.' },
      { time: '25-58', title: 'Power + Kraft', work: 'CMJ, MB Rotational/Scoop, Squat/Trap Bar, Pull, DB Press.' },
      { time: '58-90', title: 'Robustheit + Conditioning', work: 'Neck Iso, Calf/Soleus, Pallof/Dead Bug, Band ER, 6-8x80 m oder Airbike/Erg.' },
    ],
    materials: ['MB', 'Trap Bar/DB', 'Baender', 'Airbike/Erg optional'],
    safetyNotes: ['Schwere Beine = kuerzen.', 'Kein Finisher.'],
    coachNotes: ['Kuerzen: Conditioning zuerst, dann Kraftsatz.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw30-di-2026-07-21',
    date: '2026-07-21',
    kw: 'KW30',
    title: 'Dienstag 21. Juli: Session 5A',
    type: 'training',
    summary: 'Hoechste Dichte, keine Maximaltests, rugby-naehere Wiederholungsbelastung. RPE 7-8 nur fuer stabile Gruene.',
    primarySource: 'plans/offseason_coach_sheets/kw28_31_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw28To31Cards, pdfRefs.exerciseMapping],
    goals: ['hoechste Dichte', 'Rugby-naehere Wiederholungsbelastung', 'keine Maximaltests'],
    timeline: [
      { time: '0-30', title: 'Check-in + Prep + Speed/COD', work: 'Schlaf/Stress, Y weniger Dichte, RAMP, Plant/Cut Prep, Accel, Decel Zone, 45-Grad-Cut.' },
      { time: '30-66', title: 'Power + Kraft Pods', work: 'Broad Jump, MB Chest/Scoop, Trap Bar/Squat 4x4, Bench/DB + Row/Pull-up, RFESS + Carry.' },
      { time: '66-90', title: 'Cluster + Microdose + Conditioning', work: 'CF Sled, HY Accel-to-Brace/Decel, SB Hamstring/Calf + Fly-in, Ball-in-Play Waves.' },
    ],
    materials: ['Huetchen', 'MB', 'Trap Bar/DB', 'Sled optional', 'Baender'],
    safetyNotes: ['Stoppsignal: Technik bricht, Sprintqualitaet faellt, Schmerzen steigen.'],
    coachNotes: ['Y bekommt weniger Dichte; nicht alles gleichzeitig steigern.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw30-do-2026-07-23',
    date: '2026-07-23',
    kw: 'KW30',
    title: 'Donnerstag 23. Juli: Session 5B',
    type: 'training',
    summary: 'Bewegungsschaerfe, kleines Kraftsignal, keine kumulative Ermuedung. RPE 5-6.',
    primarySource: 'plans/offseason_coach_sheets/kw28_31_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw28To31Cards, pdfRefs.exerciseMapping],
    goals: ['Bewegungsschaerfe', 'kleines Kraftsignal', 'keine Zusatzermuedung'],
    timeline: [
      { time: '0-24', title: 'Check-in + Prep + Speed', work: 'Ampel, Muskelkater, RAMP kurz, 3-4 hochwertige Reps 20-30 m.' },
      { time: '24-55', title: 'Power + Kraft', work: 'Jump, MB, Trap Bar/Squat, Row/Pull, Carry.' },
      { time: '55-90', title: 'Robustheit + Conditioning + Abschluss', work: 'Soleus/Calf, Neck Iso, Adductor, Side Plank, 8-10 min Tempo oder Airbike/Erg, August vorbereiten.' },
    ],
    materials: ['MB', 'Trap Bar/DB', 'Baender', 'Airbike/Erg optional'],
    safetyNotes: ['Nach harter Dienstagseinheit stark kuerzen.', 'Nur gute Speed-Reps.'],
    coachNotes: ['Bei mueder Gruppe nur Prep, Speed, Power und kurze Robustheit.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw31-di-2026-07-28',
    date: '2026-07-28',
    kw: 'KW31',
    title: 'Dienstag 28. Juli: Session 6A',
    type: 'recheck',
    summary: 'Fortschritt sichtbar machen ohne Testtag, Kraft/Sprint konsolidieren und August vorbereiten. RPE 6-7.',
    primarySource: 'plans/offseason_coach_sheets/kw28_31_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw28To31Cards, pdfRefs.exerciseMapping, pdfRefs.preAugustOverview],
    goals: ['optional Mini-Recheck', 'Kraft/Sprint konsolidieren', 'August-Verfuegbarkeit klaeren'],
    timeline: [
      { time: '0-30', title: 'Check-in + Prep + Mini-Recheck', work: 'Ampel und August-Verfuegbarkeit, RAMP, Landing, Neck/Shoulder, optional Broad Jump + 20-30 m nur frisch.' },
      { time: '30-62', title: 'Power + Kraft Pods', work: 'MB Throw, Hauptlift, Push/Pull, Unilateral + Carry.' },
      { time: '62-90', title: 'Microdose + Conditioning + August-Regeln', work: 'Nordic/Copenhagen/Calf, Ball-in-Play oder Tempo, No-Gos klaeren.' },
    ],
    materials: ['MB', 'Trap Bar/DB', 'Baender', 'Tempo-Flaeche'],
    safetyNotes: ['Mini-Recheck streichen, wenn Anwesenheit unregelmaessig oder Gruppe nicht frisch ist.'],
    coachNotes: ['Fortschritt zeigen, aber keinen Testabend daraus machen.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw31-do-2026-07-30',
    date: '2026-07-30',
    kw: 'KW31',
    title: 'Donnerstag 30. Juli: Session 6B',
    type: 'transition',
    summary: 'Sauberer Abschluss vor Abreise, bekannte Uebungen festigen, August-Uebergang vorbereiten. RPE 5-6.',
    primarySource: 'plans/offseason_coach_sheets/kw28_31_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw28To31Cards, pdfRefs.preAugustOverview],
    goals: ['Abschluss vor Abreise', 'bekannte Uebungen festigen', 'August-Uebergang vorbereiten'],
    timeline: [
      { time: '0-24', title: 'Check-in + Prep + Speed', work: 'Ampel, offene Returner-/Schmerzinfos, kurze RAMP, 3x20 m smooth fast.' },
      { time: '24-58', title: 'Power + Krafttechnik', work: 'leichte MB Throws, CMJ + Stick, bekannte Hauptmuster 2-3x5.' },
      { time: '58-90', title: 'August Prep + Robustheit + Abschluss', work: 'Squat/Hinge/Push/Pull/Carry reviewen, simple Laufoptionen, Hamstring/Adductor/Calf/Shoulder/Trunk, No-Gos.' },
    ],
    materials: ['MB', 'DB/KB', 'Baender', 'August-Unterlagen'],
    safetyNotes: ['No-Go: neue komplexe Uebung, harte Kontaktspitze, Max-Sprints unter Ermuedung.'],
    coachNotes: ['August-Notizen und Verfuegbarkeit sichern.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
]

function toLocalDateKey(date: Date) {
  const year = date.getFullYear()
  const month = `${date.getMonth() + 1}`.padStart(2, '0')
  const day = `${date.getDate()}`.padStart(2, '0')
  return `${year}-${month}-${day}`
}

export function getRelevantSessions(today = new Date()) {
  const todayKey = toLocalDateKey(today)
  const upcomingIndex = sessionDefinitions.findIndex((session) => session.date >= todayKey)

  if (upcomingIndex === -1) {
    return {
      featuredSession: sessionDefinitions[sessionDefinitions.length - 1],
      upcomingSessions: sessionDefinitions.slice(-2),
    }
  }

  return {
    featuredSession: sessionDefinitions[upcomingIndex],
    upcomingSessions: sessionDefinitions.slice(upcomingIndex, upcomingIndex + 2),
  }
}
