import { pdfRefs } from './pdfRefs'
import type { SessionBlock, SessionDefinition } from './types'

type SessionBlockDraft = Omit<SessionBlock, 'key'> & {
  slug: string
}

function sessionBlocks(sessionId: string, blocks: SessionBlockDraft[]): SessionBlock[] {
  return blocks.map(({ slug, ...block }) => ({
    ...block,
    key: `${sessionId}:${slug}`,
  }))
}

export const sessionDefinitions: SessionDefinition[] = [
  {
    id: 'kw25-di-2026-06-16',
    date: '2026-06-16',
    kw: 'KW25',
    title: 'Dienstag 16. Juni: Onboarding + Bewegung',
    type: 'training',
    summary:
      'Kennenlernen, Ampel setzen, Schmerzen/Returner grob erfassen, Bewegung beobachten und leicht trainieren. Kein Testtag.',
    primarySource: 'plans/offseason_coach_sheets/KW25_tuesday_training_plan_clear_2026-06-16.md',
    pdfRefs: [pdfRefs.kw25TuesdayPlan, pdfRefs.kw25TuesdayCoachScript, pdfRefs.coachCardTuesday],
    goals: [
      'Kennenlernen und Trainingskultur setzen',
      'Ampel, Schmerz, Life-Flag und Returnerstatus grob erfassen',
      'Bewegung beobachten und leicht trainieren',
      'Kein Ranking, kein Bronco, kein 30-m-Test',
    ],
    timeline: sessionBlocks('kw25-di-2026-06-16', [
      {
        slug: 'arrival',
        order: 10,
        time: '0-8',
        title: 'Ankommen',
        work: 'Namen sammeln, Blatt starten, Einwilligung falls noetig.',
        dose: 'ruhig',
        note: 'Name eintragen',
        libraryRefs: ['coach-script-kw25'],
      },
      {
        slug: 'team-brief',
        order: 20,
        time: '8-14',
        title: 'Teamansage',
        work: 'Ziel, Ampel und ehrliche Rueckmeldung erklaeren.',
        dose: '60 Sekunden',
        note: 'Testdruck rausnehmen',
        libraryRefs: ['coach-script-kw25', 'spieler-briefing-start'],
      },
      {
        slug: 'readiness-check',
        order: 30,
        time: '14-24',
        title: 'Kurzcheck',
        work: 'Position, Readiness, Schmerz + Ort, Life-Flag und Returnerstatus.',
        dose: 'pro Spieler kurz',
        note: 'Ampel setzen',
        libraryRefs: ['detail-briefing-unit-1'],
      },
      {
        slug: 'ramp-warmup',
        order: 40,
        time: '24-36',
        title: 'Warm-up',
        work: 'Lauf 1x20 m, rueckwaerts 1x20 m, Shuffle 1x20 m/Seite, A-March, Dribble, Pogo, Snap-down.',
        dose: 'RPE 2-3',
        note: 'Laufbild und Schmerz beobachten',
        exposureTags: ['mobility', 'neck_trunk'],
        libraryRefs: ['exercise-mapping-offseason'],
      },
      {
        slug: 'movement-screen',
        order: 50,
        time: '36-46',
        title: 'Movement Check',
        work: 'Adductor Squeeze, Ankle/Calf, Push-up Plus/Incline, Single-leg Bridge, Self-Neck-ISO nur symptomfrei.',
        dose: 'nur beobachten',
        note: 'nur Auffaelliges notieren',
        exposureTags: ['mobility', 'neck_trunk'],
        libraryRefs: ['exercise-mapping-offseason'],
      },
      {
        slug: 'technique-patterns-1',
        order: 60,
        time: '46-58',
        title: 'Technik 1',
        work: 'Squat, Hinge, Push, Row und Carry.',
        dose: '2 Runden, RPE 4-5',
        note: 'Technikstandard setzen',
        exposureTags: ['lower_strength', 'upper_strength'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'speed-prep',
        order: 70,
        time: '58-68',
        title: 'Speed Prep',
        work: '3x15 m bei 60/70/80 Prozent, optional 2x20 m nur Gruen.',
        dose: '60-90 s Gehpause',
        note: 'kein Timing',
        exposureTags: ['speed', 'acceleration'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'technique-patterns-2',
        order: 80,
        time: '68-80',
        title: 'Technik 2',
        work: 'Split Squat, DB/KB DL, MB Chest Pass technisch, Band ER, Dead Bug.',
        dose: '1-2 Runden, RPE 4-5',
        note: 'keine Weiten messen',
        exposureTags: ['power', 'lower_strength', 'upper_strength', 'neck_trunk'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'easy-finish',
        order: 90,
        time: '80-86',
        title: 'Lockerer Abschluss',
        work: '4x40 m locker nur Gruen oder Mobility.',
        dose: '60-70 Prozent',
        note: 'optional',
        exposureTags: ['conditioning'],
        libraryRefs: ['variants-abcd'],
      },
      {
        slug: 'closeout',
        order: 100,
        time: '86-90',
        title: 'Abschluss',
        work: 'sRPE 0-10, Schmerz nach Einheit, Donnerstag-Entscheidung.',
        note: 'sRPE, Beschwerden, E2',
        libraryRefs: ['coach-script-kw25'],
      },
    ]),
    materials: ['Klemmbrett', 'Check-in-Blatt', 'Huetchen', 'DB/KB', 'Med-Ball', 'Baender', 'Carry-Flaeche'],
    safetyNotes: [
      'Dienstag ist kein Testtag und kein Ranking.',
      'Gelb: 30-50 Prozent weniger, kein harter Sprint, keine Zusatzkondition.',
      'Rot: kein normales Training; Kopf/Nacken/Concussion/neurologisch medizinisch klaeren.',
      'Keine Diagnosen aufschreiben.',
    ],
    coachNotes: [
      'Bei Zeitdruck zuerst lockeren Abschluss streichen.',
      'Bei grosser oder chaotischer Gruppe keine optionalen 20 m und keinen lockeren Abschluss.',
      'Nachher Gelb/Rot, Returner/offen und Donnerstag-Entscheidung markieren.',
    ],
    libraryRefs: ['coach-script-kw25', 'spieler-briefing-start', 'detail-briefing-unit-1', 'variants-abcd'],
  },
  {
    id: 'kw25-do-2026-06-18',
    date: '2026-06-18',
    kw: 'KW25',
    title: 'Donnerstag 18. Juni: Training + Mini-Baseline optional',
    type: 'baseline',
    summary:
      'Reaktion auf Dienstag pruefen, Grundmuster sauber trainieren und optional zwei einfache Startwerte sammeln, nur wenn die Gruppe ruhig ist.',
    primarySource: 'plans/offseason_coach_sheets/KW25_thursday_training_plan_clear_2026-06-18.md',
    pdfRefs: [
      pdfRefs.kw25ThursdayPlan,
      pdfRefs.kw25ThursdayCheckIn,
      pdfRefs.kw25ThursdayDeepPlaybook,
      pdfRefs.thursdayCompact,
    ],
    goals: [
      'Reaktion auf Dienstag pruefen',
      'Grundmuster sauber trainieren',
      'Optional Broad Jump und Med-Ball Chest Pass erfassen',
      'Kein 30-m-Test und kein Bronco',
    ],
    timeline: sessionBlocks('kw25-do-2026-06-18', [
      {
        slug: 'check-in',
        order: 10,
        time: '0-8',
        title: 'Check-in',
        work: 'Ampel, Reaktion auf Dienstag, neue Schmerzen und Returner-Limit.',
        note: 'Ampel, Schmerz, Ret',
        libraryRefs: ['deep-playbook-donnerstag-kw25'],
      },
      {
        slug: 'warm-up',
        order: 20,
        time: '8-18',
        title: 'Warm-up',
        work: 'Lauf 2x20 m, Shuffle, A-March, Dribble, Pogo, Snap-down.',
        dose: 'RPE 2-3',
        note: 'Laufbild',
        exposureTags: ['mobility', 'neck_trunk'],
        libraryRefs: ['exercise-mapping-offseason'],
      },
      {
        slug: 'speed',
        order: 30,
        time: '18-28',
        title: 'Speed',
        work: '4x10 m plus optional 2x15 m.',
        dose: '70-80 Prozent, 60-90 s Gehpause',
        note: 'kein Timing',
        exposureTags: ['speed', 'acceleration'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'mini-baseline',
        order: 40,
        time: '28-40',
        title: 'Mini-Baseline optional',
        work: 'Broad Jump 2 Versuche und MB Chest Pass 2 Versuche.',
        dose: 'nur wenn ruhig',
        note: 'kein Ranking',
        exposureTags: ['power'],
        libraryRefs: ['deep-playbook-donnerstag-kw25'],
      },
      {
        slug: 'strength-pods',
        order: 50,
        time: '40-64',
        title: 'Kraft Pods',
        work: 'Squat, Hinge, Push/Pull und Carry.',
        dose: 'RPE 5-6, 45-75 s Wechselpause',
        note: 'Technik/Last grob',
        exposureTags: ['lower_strength', 'upper_strength'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'microdose',
        order: 60,
        time: '64-74',
        title: 'Microdose',
        work: 'Adductor Squeeze, Calf Raise, Band ER, Dead Bug oder Side Plank, Self-Neck-ISO nur symptomfrei.',
        dose: 'schmerzfrei',
        note: 'Problem ja/nein',
        exposureTags: ['neck_trunk', 'mobility'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'easy-tempo',
        order: 70,
        time: '74-84',
        title: 'Easy Tempo',
        work: '6x40-60 m locker oder 6-8 min Bike/Erg.',
        dose: '60-70 Prozent, sprechen koennen',
        note: 'nur wenn gemacht',
        exposureTags: ['conditioning'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'closeout',
        order: 80,
        time: '84-90',
        title: 'Abschluss',
        work: 'sRPE, Beschwerden/Issue und KW26-Hinweis.',
        note: 'sRPE, Beschwerden',
        libraryRefs: ['deep-playbook-donnerstag-kw25'],
      },
    ]),
    materials: ['Huetchen', 'DB/KB', 'Med-Ball', 'Baender', 'Carry-Flaeche', 'Bike/Erg optional'],
    safetyNotes: [
      'Mini-Baseline nur wenn ruhig, sicher und genug Platz vorhanden ist.',
      'Spieler nicht ranken; Vergleich ist spaeter mit sich selbst.',
      'Bei vielen Gelb/Rot: keine Mini-Baseline, Speed reduzieren, kein Easy Tempo.',
      '30 m und Bronco bleiben nicht aktiv verpflichtend.',
    ],
    coachNotes: [
      'Bei Zeitdruck zuerst Easy Tempo streichen, dann Mini-Baseline.',
      'Bei Regen/rutschigem Feld keine Jumps/Speed, stattdessen Bike/Erg oder Technikpods.',
      'Wenn keine Werte entstehen, nichts nachholen erzwingen.',
    ],
    libraryRefs: [
      'deep-playbook-donnerstag-kw25',
      'coach-script-kw25',
      'variants-abcd',
      'exercise-mapping-offseason',
    ],
  },
  {
    id: 'kw26-di-2026-06-23',
    date: '2026-06-23',
    kw: 'KW26',
    title: 'Dienstag 23. Juni: einzige KW26-Einheit',
    type: 'training',
    summary:
      'Nur eine S&C-Einheit in dieser Woche: Track-Technik, kurze Beschleunigung, Deadlift/Bulgarian/Push-Pull/Carry und gezielte Nachholer. Kein Donnerstag-Nachholen.',
    primarySource: 'plans/offseason_coach_sheets/KW26_basis_1.md',
    pdfRefs: [
      pdfRefs.kw26TuesdayTrainingCompact,
      pdfRefs.kw26TuesdayCheckIn,
      pdfRefs.kw26TuesdayDeepPlaybook,
      pdfRefs.exerciseMapping,
    ],
    goals: [
      'Koordinative Track-Technik stabilisieren',
      '10-20 m Beschleunigung dosiert trainieren',
      'Kraftbasis mit Deadlift, Bulgarian Split Squat, Push/Pull und Carry setzen',
      'Nachholtests nur fuer offene Einzelfaelle, kein Team-Retest',
    ],
    timeline: sessionBlocks('kw26-di-2026-06-23', [
      {
        slug: 'check-in',
        order: 10,
        time: '0-5',
        title: 'Check-in',
        work: 'Ampel, Schmerz, Returner, Kopf/Nacken-Flag und Nachholfaelle erfassen.',
        note: '2-Seiten-PDF nutzen',
        exercises: [
          {
            key: 'kw26-checkin-traffic',
            name: 'Check-in Status',
            prescription: 'Pro Spieler Ampel, Schmerz, Returnerstatus, Kopf/Nacken-Flag und offene Nachholfaelle kurz erfassen.',
            coachingCues: ['Kurz und ehrlich abfragen', 'Rot/Gelb sofort fuer Varianten vormerken'],
            setup: 'Check-in-PDF oder bestehende Check-in-Liste am Feld nutzen.',
            safety: 'Kopf/Nacken/Schwindel/neurologisch = Rot und medizinisch klaeren.',
            targeting: 'all',
            recording: 'observation',
          },
        ],
        libraryRefs: ['kw26-tuesday-active-pack'],
      },
      {
        slug: 'mobility-activation',
        order: 20,
        time: '5-13',
        title: 'Mobility / Activation',
        work: 'Hip Switch, Adductor Rockback, Knee-to-Wall, Deep Squat Pry, Open Book, Glute Bridge.',
        dose: 'RPE 2-3',
        note: 'gemeinsam halten',
        exposureTags: ['mobility', 'neck_trunk'],
        exercises: [
          {
            key: 'kw26-hip-switch',
            name: 'Hip Switch',
            prescription: '5/Seite.',
            coachingCues: ['Huefte ruhig oeffnen', 'Kontrolliert wechseln'],
            setup: 'Gemeinsam am Boden, genug Abstand zwischen Spielern.',
            targeting: 'all',
            recording: 'none',
          },
          {
            key: 'kw26-adductor-rockback',
            name: 'Adductor Rockback',
            prescription: '6/Seite.',
            coachingCues: ['Ruecken lang lassen', 'Nur schmerzfreie Range nutzen'],
            regression: 'Range kuerzen oder breiter abstuetzen.',
            targeting: 'all',
            recording: 'none',
          },
          {
            key: 'kw26-knee-to-wall',
            name: 'Knee-to-Wall',
            prescription: '8/Seite.',
            coachingCues: ['Ferse bleibt am Boden', 'Knie folgt Fusslinie'],
            targeting: 'all',
            recording: 'none',
          },
          {
            key: 'kw26-deep-squat-pry',
            name: 'Deep Squat Pry',
            prescription: '3 Atemzuege + 3 Squat-to-Stand.',
            coachingCues: ['Ruhig atmen', 'Fuesse stabil halten'],
            regression: 'Hoeher greifen oder Range kuerzen.',
            targeting: 'all',
            recording: 'none',
          },
          {
            key: 'kw26-open-book',
            name: 'Open Book',
            prescription: '6/Seite.',
            coachingCues: ['Blick folgt Hand', 'Becken bleibt ruhig'],
            targeting: 'all',
            recording: 'none',
          },
          {
            key: 'kw26-glute-bridge',
            name: 'Glute Bridge',
            prescription: '20s halten + 5 Wiederholungen.',
            coachingCues: ['Rippen unten halten', 'Aus der Huefte strecken'],
            targeting: 'all',
            recording: 'none',
          },
        ],
        libraryRefs: ['exercise-mapping-offseason'],
      },
      {
        slug: 'track-technique',
        order: 30,
        time: '13-25',
        title: 'Track-Technik',
        work: 'A-March, A-March Stick, Seitshuffle, Pogo und Snap-down. Dribble nicht erzwingen.',
        note: 'Koordination vor Komplexitaet',
        exposureTags: ['mobility', 'neck_trunk'],
        exercises: [
          {
            key: 'kw26-a-march',
            name: 'A-March',
            prescription: '2x10 m.',
            coachingCues: ['Gross bleiben', 'Fuss unter den Koerper setzen'],
            setup: '10-m-Bahn mit klarer Ruecklaufzone.',
            targeting: 'all',
            recording: 'none',
            exerciseKey: 'ramp_sequence',
          },
          {
            key: 'kw26-a-march-stick',
            name: 'A-March Stick',
            prescription: '1x10 m.',
            coachingCues: ['Oben kurz stabilisieren', 'Kein Tempo erzwingen'],
            targeting: 'all',
            recording: 'none',
            exerciseKey: 'ramp_sequence',
          },
          {
            key: 'kw26-side-shuffle',
            name: 'Seitshuffle',
            prescription: '1x10 m/Seite.',
            coachingCues: ['Huefte tief und ruhig', 'Fuesse nicht kreuzen'],
            targeting: 'all',
            recording: 'none',
          },
          {
            key: 'kw26-pogo',
            name: 'Pogo',
            prescription: '2x10 Kontakte.',
            coachingCues: ['Leise, elastische Kontakte', 'Koerper lang halten'],
            targeting: 'all',
            recording: 'none',
            exerciseKey: 'ramp_sequence',
          },
          {
            key: 'kw26-snap-down-stick',
            name: 'Snap-down + Stick',
            prescription: '2x3.',
            coachingCues: ['Athletisch landen', 'Knie stabil ueber Fuss'],
            safety: 'Bei Schmerz oder schlechter Landung abbrechen oder regressieren.',
            targeting: 'all',
            recording: 'observation',
            exerciseKey: 'ramp_sequence',
          },
        ],
        libraryRefs: ['exercise-mapping-offseason'],
      },
      {
        slug: 'acceleration',
        order: 40,
        time: '25-38',
        title: 'Acceleration',
        work: 'Forwards 5x10 m, Hybrid 4x10 m + 2x15 m, Backs 3x10 m + 2x20 m smooth build-up.',
        note: 'keine Rennen',
        exposureTags: ['speed', 'acceleration'],
        exercises: [
          {
            key: 'kw26-accel-forwards',
            name: 'Forwards Acceleration',
            prescription: '5x10 m, vollstaendige Rueckgehpause.',
            coachingCues: ['Starker erster Schritt', 'Nicht gegeneinander rennen'],
            safety: 'Nur Gruen/geeignet; Returner/offen kein harter Sprint.',
            targeting: 'cluster',
            clusters: ['front_row', 'locks', 'back_row'],
            recording: 'observation',
            exerciseKey: 'acceleration_10_20m',
          },
          {
            key: 'kw26-accel-hybrid',
            name: 'Hybrid Acceleration',
            prescription: '4x10 m + 2x15 m, smooth fast.',
            coachingCues: ['Saubere Linie', 'Qualitaet vor Intensitaet'],
            targeting: 'cluster',
            clusters: ['halves', 'centres', 'offen'],
            recording: 'observation',
            exerciseKey: 'acceleration_10_20m',
          },
          {
            key: 'kw26-accel-backs',
            name: 'Backs Acceleration',
            prescription: '3x10 m + 2x20 m smooth build-up.',
            coachingCues: ['Progressiv beschleunigen', 'Locker bleiben'],
            targeting: 'cluster',
            clusters: ['back_three'],
            recording: 'observation',
            exerciseKey: 'acceleration_10_20m',
          },
        ],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'make-up-tests',
        order: 50,
        time: '38-45',
        title: 'Nachholer',
        work: 'Artur Med-Ball mit Ballgewicht. Christopher/David Broad Jump nur nach sauberer Landung. DAmore 9.5 m korrigieren. ACL-Returner kein Jump/Sprint/COD.',
        note: 'kein Team-Retest',
        exposureTags: ['power'],
        exercises: [
          {
            key: 'kw26-artur-med-ball',
            name: 'Artur Med-Ball',
            prescription: 'Med-Ball-Wurf nachholen; Ballgewicht im Kontext notieren.',
            coachingCues: ['Gleicher Ball wie Referenz nutzen', 'Weite sauber messen'],
            targeting: 'named',
            playerNames: ['Artur'],
            recording: 'metric',
            metricKey: 'med_ball_chest_pass',
          },
          {
            key: 'kw26-christopher-david-broad-jump',
            name: 'Christopher/David Broad Jump',
            prescription: 'Nur nach 2 sauberen Landungen, maximal 2 Versuche.',
            coachingCues: ['Stick-Landung zaehlt vor Weite', 'Kein Re-Test bei unsauberer Landung'],
            safety: 'Bei Schmerz, Unsicherheit oder Returnerstatus auslassen.',
            targeting: 'named',
            playerNames: ['Christopher', 'David'],
            recording: 'metric',
            metricKey: 'broad_jump',
          },
          {
            key: 'kw26-damore-throw-correction',
            name: "D'Amore Wurfweite korrigieren",
            prescription: '9.5 m als Wurfweite korrigieren.',
            coachingCues: ['Nur Datenkorrektur, kein Zusatztest'],
            targeting: 'named',
            playerNames: ["D'Amore", 'DAmore'],
            recording: 'metric',
            metricKey: 'med_ball_chest_pass',
          },
          {
            key: 'kw26-acl-returner-rule',
            name: 'ACL-Returner Regel',
            prescription: 'Kein Jump, kein Sprint, kein COD.',
            coachingCues: ['Alternative Mobility/leichtes Kraftmuster waehlen', 'Keine medizinische Entscheidung ableiten'],
            safety: 'Nur nach Physio-/Medical-Vorgaben belasten.',
            targeting: 'returner',
            returnerRule: 'ACL/offener Returner: Jump/Sprint/COD auslassen.',
            recording: 'observation',
          },
        ],
        libraryRefs: ['kw26-tuesday-active-pack'],
      },
      {
        slug: 'strength-pods',
        order: 60,
        time: '45-73',
        title: 'Kraft-Pods',
        work: 'A Deadlift, B Bulgarian Split Squat, C Push/Pull, D Carry.',
        dose: 'RPE 6-7 beim Deadlift, sonst RPE 6',
        note: 'keine Grind-Reps',
        exposureTags: ['lower_strength', 'upper_strength'],
        exercises: [
          {
            key: 'kw26-deadlift',
            name: 'Deadlift',
            prescription: '3x5 @ RPE 6-7.',
            coachingCues: ['Bar/KB eng am Koerper', 'Keine Grind-Reps'],
            regression: 'KB/DB Deadlift statt Trap Bar.',
            targeting: 'all',
            recording: 'exercise',
            exerciseKey: 'trap_bar_deadlift',
          },
          {
            key: 'kw26-bulgarian-split-squat',
            name: 'Bulgarian Split Squat',
            prescription: '2-3x6/Seite @ RPE 6.',
            coachingCues: ['Kontrollierte Tiefe', 'Vorderes Knie stabil'],
            regression: 'Split Squat oder Reverse Lunge.',
            targeting: 'all',
            recording: 'exercise',
            exerciseKey: 'split_squat_rfess',
          },
          {
            key: 'kw26-push-pull',
            name: 'Push/Pull',
            prescription: '3x6-8 Push + 3x8 Pull @ RPE 6.',
            coachingCues: ['Schulter schmerzfrei', 'Rumpf ruhig halten'],
            regression: 'Incline Push-up, Band Row oder leichtere DB.',
            targeting: 'all',
            recording: 'exercise',
            exerciseKey: 'db_press',
          },
          {
            key: 'kw26-carry',
            name: 'Carry',
            prescription: '2-3x15-20 m.',
            coachingCues: ['Gross bleiben', 'Rumpf stabil, keine Schieflage'],
            targeting: 'all',
            recording: 'exercise',
            exerciseKey: 'farmer_suitcase_carry',
          },
        ],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'position-module',
        order: 70,
        time: '73-83',
        title: 'Positionsmodul',
        work: 'Forwards Neck/Brace/Sled, Hybrid Decel/Adductor/MB, Backs Calf/Soleus/Hamstring.',
        note: 'bei Chaos kuerzen',
        exposureTags: ['cod_decel', 'contact_prep', 'neck_trunk', 'power'],
        exercises: [
          {
            key: 'kw26-position-forwards',
            name: 'Forwards Neck/Brace/Sled',
            prescription: 'Kurzer kontrollierter Block: Neck ISO, Brace ISO oder Sled March nach Verfuegbarkeit.',
            coachingCues: ['Kontrolliert und technisch', 'Kein Full Contact'],
            safety: 'Kopf/Nacken-Symptome = auslassen und klaeren.',
            targeting: 'cluster',
            clusters: ['front_row', 'locks', 'back_row'],
            recording: 'observation',
            exerciseKey: 'sled_march',
          },
          {
            key: 'kw26-position-hybrid',
            name: 'Hybrid Decel/Adductor/MB',
            prescription: 'Decel-Technik leicht, Adductor-Microdose oder Med-Ball technisch.',
            coachingCues: ['Leise abbremsen', 'Adduktor schmerzfrei halten'],
            targeting: 'cluster',
            clusters: ['halves', 'centres', 'offen'],
            recording: 'observation',
            exerciseKey: 'copenhagen_squeeze',
          },
          {
            key: 'kw26-position-backs',
            name: 'Backs Calf/Soleus/Hamstring',
            prescription: 'Calf/Soleus plus Hamstring-Microdose, kurze saubere Saetze.',
            coachingCues: ['Volle Kontrolle', 'Keine Ermuedungsjagd'],
            targeting: 'cluster',
            clusters: ['back_three'],
            recording: 'observation',
            exerciseKey: 'calf_soleus_raise',
          },
        ],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'finish-closeout',
        order: 80,
        time: '83-90',
        title: 'Optional Finish + Abschluss',
        work: 'Nur wenn ruhig: 4x60 m Tempo bei 60-70 Prozent. Danach sRPE, Beschwerden/Issue und KW27-Notiz.',
        note: 'Finish zuerst streichen',
        exposureTags: ['conditioning'],
        exercises: [
          {
            key: 'kw26-optional-tempo',
            name: 'Optional Tempo',
            prescription: 'Nur wenn ruhig: 4x60 m bei 60-70 Prozent.',
            coachingCues: ['Locker und technisch', 'Nicht als harter Finisher nutzen'],
            safety: 'Bei Zeitdruck, Chaos, Gelb/Rot oder Returnerstatus zuerst streichen.',
            targeting: 'optional',
            recording: 'observation',
            exerciseKey: 'easy_tempo_run',
          },
          {
            key: 'kw26-closeout',
            name: 'Closeout',
            prescription: 'sRPE, Beschwerden/Issue und KW27-Notiz erfassen.',
            coachingCues: ['Kurz direkt nach der Einheit abfragen', 'Auffaelliges fuer naechste Woche markieren'],
            targeting: 'all',
            recording: 'observation',
          },
        ],
        libraryRefs: ['kw26-tuesday-active-pack'],
      },
    ]),
    materials: ['Klemmbrett', 'Check-in-PDF', 'Huetchen', 'MB', 'DB/KB', 'Baender', 'Carry-Flaeche', 'Trap Bar optional', 'Sled optional'],
    safetyNotes: [
      'Donnerstag wird nicht nachgeholt; keine Belastungsspitze als Ersatz.',
      'Kein Team-Broad-Jump-Retest, kein Bronco, kein Max-Sprint, kein Max-Deadlift.',
      'Kopf/Nacken/Schwindel/neurologisch = Rot, raus aus normalem Training und medizinisch klaeren.',
      'Returner/offen: kein harter Sprint, kein Jump, kein COD, kein Conditioning.',
    ],
    coachNotes: [
      'Bei Chaos zuerst Finish streichen, dann Positionsmodul kuerzen, dann Nachholtests auf Artur beschraenken.',
      'Dribble ist nicht Pflicht; A-March, Shuffle, Pogo und Snap-down reichen diese Woche.',
      'Deadlift ist 3x5 bei RPE 6-7, kein 5RM-Test.',
    ],
    libraryRefs: ['kw26-tuesday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw26-do-2026-06-25',
    date: '2026-06-25',
    kw: 'KW26',
    title: 'Donnerstag 25. Juni: Session 1B',
    type: 'training',
    summary: 'Zweiter Ganzkoerperreiz ohne hohe Ermuedung; Landen, Bremsen und Power. RPE 5-6.',
    primarySource: 'plans/offseason_coach_sheets/kw25_27_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw25To27Cards, pdfRefs.exerciseMapping],
    goals: ['Qualitaet halten', 'Landen/Bremsen vorbereiten', 'Bronco nicht noetig'],
    timeline: sessionBlocks('kw26-do-2026-06-25', [
      {
        slug: 'checkin-prep-speed',
        order: 10,
        time: '0-24',
        title: 'Check-in + Prep + Speed',
        work: 'Ampel, Muskelkater, kurze RAMP, Pogo, Dribble, Snap-down, 3-4x20 m smooth fast.',
        exposureTags: ['mobility', 'speed', 'acceleration'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'power-strength',
        order: 20,
        time: '24-58',
        title: 'Power + Kraft',
        work: 'MB Scoop, Low Box/Squat Jump, KB/Trap Bar DL, Push/Pull, Step-up/Reverse Lunge.',
        exposureTags: ['power', 'lower_strength', 'upper_strength'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'robustness-conditioning',
        order: 30,
        time: '58-90',
        title: 'Robustheit + Conditioning',
        work: 'Calf, Band ER, Side Plank, lockere Tempo Runs oder Bike/Erg, Abschluss.',
        exposureTags: ['neck_trunk', 'conditioning'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
    ]),
    materials: ['MB', 'Box optional', 'KB/Trap Bar', 'Baender', 'Bike/Erg optional'],
    safetyNotes: ['Bei starker Dienstag-Reaktion kuerzen.', 'Bronco in KW26 nicht noetig.'],
    coachNotes: ['Kein Finisher; Conditioning bleibt locker-moderat.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw27-di-2026-06-30',
    date: '2026-06-30',
    kw: 'KW27',
    title: 'Dienstag 30. Juni: Session 2A',
    type: 'training',
    summary: 'Beschleunigung stabilisieren, Kraftumfang leicht steigern, erste Cluster-Farbe. RPE 6-7.',
    primarySource: 'plans/offseason_coach_sheets/KW27_tuesday_training_compact_2026-06-30.md',
    pdfRefs: [
      pdfRefs.kw27TuesdayTrainingCompact,
      pdfRefs.kw27TuesdayCheckIn,
      pdfRefs.kw27TuesdayDeepPlaybook,
      pdfRefs.exerciseMapping,
    ],
    goals: ['Accel-Qualitaet', 'Kraftumfang leicht steigern', 'ein Cluster-Fokus'],
    timeline: sessionBlocks('kw27-di-2026-06-30', [
      {
        slug: 'checkin-prep-speed',
        order: 10,
        time: '0-29',
        title: 'Check-in + Mobility + Track',
        work: 'Ampel, Returner, Schmerz; Hip Switch, Adductor Rockback, Knee-to-Wall, Open Book, Glute Bridge; A-March, Line Hops vor/zurueck + seitlich, Snap-down, Decel Stick; Collision Forwards 10-15 m, Hybrid 10-20 m, Speed/Space Backs smooth 20-30 m.',
        exposureTags: ['mobility', 'speed', 'acceleration'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'power-strength-pods',
        order: 20,
        time: '29-65',
        title: 'Power + Kraft Pods',
        work: 'Broad Jump, MB Punch/Chest, Trap Bar/Squat, Push/Pull, RFESS/Split Squat, Carry.',
        exposureTags: ['power', 'lower_strength', 'upper_strength'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'cluster-microdose-conditioning',
        order: 30,
        time: '65-90',
        title: 'Cluster + Microdose + Conditioning',
        work: 'Collision Forwards Sled, Hybrid Decel, Speed/Space Backs Build-up; Nordic/Copenhagen; 1 Serie Intervall als Default, 2. Serie nur bei Zeit/Qualitaet.',
        exposureTags: ['contact_prep', 'cod_decel', 'speed', 'neck_trunk', 'conditioning'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
    ]),
    materials: ['Huetchen', 'MB', 'Trap Bar/DB', 'Sled optional', 'Baender'],
    safetyNotes: ['Y: 1 Conditioning-Serie oder streichen.', 'Returner offen: kein Cluster-Speed/COD.'],
    coachNotes: ['Keine Nachholbelastung fuer verpasste Einheiten.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw27-do-2026-07-02',
    date: '2026-07-02',
    kw: 'KW27',
    title: 'Donnerstag 2. Juli: Session 2B',
    type: 'training',
    summary: 'A-Skip einfuehren, Speed/Max-V-Annaeherung dosieren, Kraftsignal erhalten, nicht ermueden. RPE 5-6.',
    primarySource: 'plans/offseason_coach_sheets/KW27_thursday_training_compact_2026-07-02.md',
    pdfRefs: [
      pdfRefs.kw27ThursdayTrainingCompact,
      pdfRefs.kw27ThursdayCheckIn,
      pdfRefs.kw27ThursdayDeepPlaybook,
      pdfRefs.exerciseMapping,
    ],
    goals: ['A-Skip einfuehren', 'Speed dosieren', 'Kraftsignal erhalten'],
    timeline: sessionBlocks('kw27-do-2026-07-02', [
      {
        slug: 'checkin-prep-speed',
        order: 10,
        time: '0-31',
        title: 'Check-in + Prep + Speed',
        work: 'Ampel/Muskelkater, Dienstag-Reaktion, kurze RAMP, A-March Reminder, A-Skip 2x10 m, Dribble, Pogo, Snap-down; Collision Forwards smooth 15-20 m, Hybrid smooth 20-25 m, Speed/Space Backs build 20 + fly 10 m nur gruen.',
        exposureTags: ['mobility', 'speed', 'acceleration'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'power-strength',
        order: 20,
        time: '31-62',
        title: 'Power + Kraft',
        work: 'CMJ + Stick, MB Rotational/Scoop; Kraftsignal mit Squat/Trap Bar, Pull/Row, DB Press/Push-up. 2 Saetze Default, RPE 5-6.',
        exposureTags: ['power', 'lower_strength', 'upper_strength'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'robustness-tempo',
        order: 30,
        time: '62-90',
        title: 'Robustheit + Tempo',
        work: 'Calf/Soleus, Neck Iso nur symptomfrei, Band ER/Scap, Dead Bug; optional 6x60 m Tempo @ 65-70 Prozent oder Bike/Erg locker. Abschluss mit sRPE und Beschwerden/Issue.',
        exposureTags: ['neck_trunk', 'conditioning'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
    ]),
    materials: ['Huetchen', 'MB', 'Trap Bar/DB', 'Pull-up/Row Setup', 'Baender', 'Tempo-Flaeche'],
    safetyNotes: ['Donnerstag nicht ermueden.', 'Kein Fly bei Gelb/Returner.', 'Nackenarbeit nur symptomfrei.'],
    coachNotes: ['Kuerzen: zuerst Tempo streichen, Kraft bleibt 2 Saetze Default.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw28-di-2026-07-07',
    date: '2026-07-07',
    kw: 'KW28',
    title: 'Dienstag 7. Juli: Nachgeholt Session 2B',
    type: 'training',
    summary:
      'Nachgeholtes Donnerstagstraining vom 02.07: A-Skip, Speed-Primer, Kraftsignal und Robustheit. Kein 3A-Nachholen.',
    primarySource: 'plans/offseason_coach_sheets/KW27_thursday_training_compact_2026-07-02.md',
    pdfRefs: [
      pdfRefs.kw27ThursdayTrainingCompact,
      pdfRefs.kw27ThursdayCheckIn,
      pdfRefs.kw27ThursdayDeepPlaybook,
      pdfRefs.exerciseMapping,
    ],
    goals: ['Nachgeholte 2B sauber abhalten', 'Speed dosieren', 'Kraftsignal erhalten', 'keine Nachholbelastung'],
    timeline: sessionBlocks('kw28-di-2026-07-07', [
      {
        slug: 'checkin-prep-speed',
        order: 10,
        time: '0-31',
        title: 'Check-in + Prep + Speed',
        work: 'Ampel/Muskelkater, Reaktion auf letzte Einheit, kurze RAMP, A-March Reminder, A-Skip 2x10 m, Dribble, Pogo, Snap-down; Collision Forwards smooth 15-20 m, Hybrid smooth 20-25 m, Speed/Space Backs build 20 + fly 10 m nur gruen.',
        exposureTags: ['mobility', 'speed', 'acceleration'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'power-strength',
        order: 20,
        time: '31-62',
        title: 'Power + Kraft',
        work: 'CMJ + Stick, MB Rotational/Scoop; Kraftsignal mit Squat/Trap Bar, Pull/Row, DB Press/Push-up. 2 Saetze Default, RPE 5-6.',
        exposureTags: ['power', 'lower_strength', 'upper_strength'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'robustness-tempo',
        order: 30,
        time: '62-90',
        title: 'Robustheit + Tempo',
        work: 'Calf/Soleus, Neck Iso nur symptomfrei, Band ER/Scap, Dead Bug; optional 6x60 m Tempo @ 65-70 Prozent oder Bike/Erg locker. Abschluss mit sRPE und Beschwerden/Issue.',
        exposureTags: ['neck_trunk', 'conditioning'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
    ]),
    materials: ['Huetchen', 'MB', 'Trap Bar/DB', 'Pull-up/Row Setup', 'Baender', 'Tempo-Flaeche'],
    safetyNotes: ['Kein 3A-Nachholen.', 'Kein Fly bei Gelb/Returner.', 'Nackenarbeit nur symptomfrei.'],
    coachNotes: ['Morgen ist die nachgeholte 2B; Kuerzen: zuerst Tempo streichen, Kraft bleibt 2 Saetze Default.'],
    libraryRefs: ['kw27-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw28-do-2026-07-09',
    date: '2026-07-09',
    kw: 'KW28',
    title: 'Donnerstag 9. Juli: Session 3A',
    type: 'training',
    summary:
      'Angepasste 3A nach nachgeholter 2B: stabiler Arbeitsreiz, kontrollierte Contact Prep ohne Full Contact, Kraftbasis. RPE 6-7 fuer Gruen.',
    primarySource: 'plans/offseason_coach_sheets/KW28_thursday_training_compact_2026-07-09.md',
    pdfRefs: [
      pdfRefs.kw28ThursdayTrainingCompact,
      pdfRefs.kw28ThursdayCheckIn,
      pdfRefs.kw28ThursdayDeepPlaybook,
      pdfRefs.exerciseMapping,
    ],
    goals: ['Angepasste 3A sauber abhalten', 'Contact Prep kontrolliert', 'Kraftbasis entwickeln', 'keine Nachholbelastung stapeln'],
    timeline: sessionBlocks('kw28-do-2026-07-09', [
      {
        slug: 'checkin-prep-speed',
        order: 10,
        time: '0-28',
        title: 'Check-in + Prep + Speed',
        work: 'Ampel, Returner, Reaktion auf nachgeholte 2B; RAMP, A-Skip, Pogo, Snap-down, 45-Grad-Plant klein, 10-20 m Speed, Collision Forwards optional Sled March.',
        exposureTags: ['mobility', 'speed', 'acceleration', 'contact_prep'],
        libraryRefs: ['kw28-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'power-strength-pods',
        order: 20,
        time: '28-64',
        title: 'Power + Kraft Pods',
        work: 'Broad Jump/DB Jump Squat, MB Chest/Scoop, Trap Bar/Squat 3x5 @ RPE 6-7, Press/Row, Split Squat/Carry. Gelb oder schwere Dienstag-Reaktion: 2 Saetze.',
        exposureTags: ['power', 'lower_strength', 'upper_strength'],
        libraryRefs: ['kw28-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'contact-microdose-conditioning',
        order: 30,
        time: '64-90',
        title: 'Contact Prep + Microdose + Conditioning',
        work: 'Brace ISO/Sled/Shield Connection nur kontrolliert, Nordic/Copenhagen/Band ER, Intervall nur bei stabiler Technik. Kein Full Contact.',
        exposureTags: ['contact_prep', 'neck_trunk', 'conditioning'],
        libraryRefs: ['kw28-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
      },
    ]),
    materials: ['Huetchen', 'MB', 'Trap Bar/DB', 'Sled/Shield optional', 'Baender'],
    safetyNotes: ['No-Go: Live-Kontakt, offene Returner in Contact Prep, Kopf/Nackenflag ignorieren.'],
    coachNotes: ['Contact Prep kurz und kontrolliert halten; bei schwerer 2B-Reaktion Conditioning streichen.'],
    libraryRefs: ['kw28-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw29-di-2026-07-14',
    date: '2026-07-14',
    kw: 'KW29',
    title: 'Dienstag 14. Juli: Session 3B',
    type: 'training',
    summary: 'Konsolidieren, Qualitaet vor Dichte, kurzer Review vor Aufbauphase. RPE 5-6.',
    primarySource: 'plans/offseason_coach_sheets/kw28_31_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw28To31Cards, pdfRefs.exerciseMapping],
    goals: ['Qualitaet konsolidieren', 'Regelmaessigkeit reviewen', 'nicht ueberladen', 'Donnerstag-Aufbau vorbereiten'],
    timeline: sessionBlocks('kw29-di-2026-07-14', [
      {
        slug: 'checkin-prep-speed',
        order: 10,
        time: '0-25',
        title: 'Check-in + Prep + Speed',
        work: 'Wochenrueckmeldung, RAMP, Dribble, Neck/Shoulder, smooth fast 20-30 m.',
        exposureTags: ['mobility', 'speed', 'acceleration', 'neck_trunk'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'power-strength',
        order: 20,
        time: '25-58',
        title: 'Power + Kraft',
        work: 'MB Throws, Low Box Jump/CMJ, Trap Bar/Squat, Row, Carry.',
        exposureTags: ['power', 'lower_strength', 'upper_strength'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'robustness-conditioning-review',
        order: 30,
        time: '58-90',
        title: 'Robustheit + Conditioning + Review',
        work: 'Calf/Soleus, Side Plank, Adductor, 8-10 min Tempo nur wenn frisch; Review: Regelmaessigkeit, Regressionen, Cluster, Returner.',
        exposureTags: ['neck_trunk', 'conditioning'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
    ]),
    materials: ['MB', 'Box optional', 'Trap Bar/DB', 'Baender', 'Tempo-Flaeche'],
    safetyNotes: ['Default kein harter Test.', 'Conditioning bei Bedarf streichen.'],
    coachNotes: ['Review: Wer ist regelmaessig da, wer bleibt Y/Returner, passen Cluster?'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw29-do-2026-07-16',
    date: '2026-07-16',
    kw: 'KW29',
    title: 'Donnerstag 16. Juli: Session 4B',
    type: 'training',
    summary: 'Sprintqualitaet und Power, Kraft erhalten, nicht zerstoeren. RPE 5-6.',
    primarySource: 'plans/offseason_coach_sheets/KW29_thursday_training_compact_2026-07-16.md',
    pdfRefs: [
      pdfRefs.kw29ThursdayDeepPlaybook,
      pdfRefs.kw29ThursdayTrainingCompact,
      pdfRefs.kw29ThursdayCheckIn,
    ],
    goals: ['Speed-/Power-Qualitaet kurz setzen', 'Kraftsignal erhalten', 'nicht zerstoeren', 'KW30 sauber vorbereiten'],
    timeline: sessionBlocks('kw29-do-2026-07-16', [
      {
        slug: 'checkin-prep-speed',
        order: 10,
        time: '0-32',
        title: 'Check-in + Prep + Speed Quality',
        work: 'Ampel, Dienstag-Reaktion, schwere Beine, Hamstring/Wade/Leiste/Kopf/Nacken; kurze RAMP, Track Prep; CF 2-3x20 m smooth oder leichter Sled Drive, HY 3x20-25 m smooth und Decel optional, SB 2-3x build 20 + fly 10 m nur gruen.',
        exposureTags: ['mobility', 'speed', 'acceleration'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'power-strength',
        order: 20,
        time: '32-62',
        title: 'Power + Kraftsignal',
        work: 'CMJ + Stick 3x2, MB Rotational/Scoop 3x3/Seite; Squat/Trap Bar 2-3x3-4 @ RPE 6-7, Pull 2-3x5-8, DB Press 2x6. Bei unklarer Dienstag-Reaktion 2 Saetze.',
        exposureTags: ['power', 'lower_strength', 'upper_strength'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'cluster-robustness-tempo',
        order: 30,
        time: '62-90',
        title: 'Cluster-Robustheit + Tempo optional',
        work: 'CF Neck Iso + Wall/Sled Drive ISO, HY Copenhagen/Squeeze + Pallof, SB Calf/Soleus + Hamstring Bridge. Tempo default streichen; nur sehr gruen: 4-6x60-80 m oder 6-8 min Bike/Erg. Abschluss mit sRPE und Beschwerden/Issue.',
        exposureTags: ['neck_trunk', 'conditioning'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
    ]),
    materials: ['Huetchen', 'MB', 'Trap Bar/DB', 'Baender', 'Airbike/Erg optional', 'Sled optional'],
    safetyNotes: [
      'Kein Fly fuer Gelb/Returner/offen oder auffaellige Hamstring/Wade/Leiste.',
      'Kopf/Nacken/neurologisch = Rot, medizinisch klaeren.',
    ],
    coachNotes: ['Kuerzen: Tempo zuerst, dann Cluster-Robustheit, dann Kraft auf 2 Saetze.'],
    libraryRefs: ['kw29-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw30-di-2026-07-21',
    date: '2026-07-21',
    kw: 'KW30',
    title: 'Dienstag 21. Juli: Session 4B',
    type: 'training',
    summary: 'Qualitaet bei reduzierter Dosis: kontrollierter Speed, kurzer Power-Primer und zwei saubere Kraftsaetze. Tempo nur als Coach-Opt-in.',
    primarySource: 'plans/offseason_coach_sheets/KW29_thursday_training_compact_2026-07-16.md',
    pdfRefs: [
      pdfRefs.kw29ThursdayDeepPlaybook,
      pdfRefs.kw29ThursdayTrainingCompact,
      pdfRefs.kw29ThursdayCheckIn,
    ],
    goals: [
      'A-Skip und Speedqualitaet bestaetigen',
      'Power niedrig dosieren',
      'zwei Kraftsaetze sauber konsolidieren',
      'Tempo nur bei passender Tageslage',
    ],
    timeline: sessionBlocks('kw30-di-2026-07-21', [
      {
        slug: 'check-in-ramp',
        order: 10,
        time: '0-13',
        title: 'Check-in + RAMP',
        work: 'Reaktion und Ist-Dosis der letzten Einheit, Readiness, Muskelkater, Schmerz und Caps; Lauf/Backpedal/Shuffle, Hip Switch, Rockback, Knee-to-Wall, Squat-to-Stand, Open Book und Bridge.',
        dose: 'RAMP RPE 2-3; Gelb/Rot und Returner-Caps vor Track festlegen.',
        note: 'Kopf/Nacken/Schwindel/neurologisch = sofort raus und medizinisch abklaeren.',
        exposureTags: ['mobility'],
        libraryRefs: ['kw29-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'track-speed-quality',
        order: 20,
        time: '13-31',
        title: 'Track + Speedqualitaet',
        work: 'A-March 1x10 m, A-Skip 2x10 m, Pogo 1x10, Snap-down 2x2; CF und HY 2x10 + 2x20 m, SB 2x10 + 2x30 m Build-up. Volle Pause, kein Fly.',
        dose: 'CF 60 m @ 80-85 %, HY 60 m @ 80-90 %, SB 80 m Build-up; keine Nachholmeter.',
        note: 'Gelb etwa halbe Reps; kein dynamisches Decel. Laufqualitaet beendet die Dosis.',
        exposureTags: ['speed', 'acceleration', 'cod_decel'],
        libraryRefs: ['kw29-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'power-primer',
        order: 30,
        time: '31-39',
        title: 'Power-Primer',
        work: 'CMJ + Stick 3x2; bekannter MB Rotational Scoop 2x2/Seite, sonst Chest Pass 2x3.',
        dose: 'Sechs Sprungkontakte; dokumentiertes Ballgewicht; keine Weitenjagd.',
        exposureTags: ['power'],
        libraryRefs: ['kw29-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'strength-consolidation',
        order: 40,
        time: '39-61',
        title: 'Kraft-Konsolidierung',
        work: 'A Hinge 2x4 @ RPE 6; B Press + Row je 2x6 @ RPE 6-7; C Split-Squat-ISO 2x15 s/Seite + Pallof 2x8/Seite.',
        dose: 'Zwei saubere Kraftsaetze sind der volle Plan; kein dritter Satz und kein Grind.',
        note: 'Bei 15-20 Spielern lieber ein sauberer Satz pro Pod als hektische Wechsel.',
        exposureTags: ['lower_strength', 'upper_strength'],
        libraryRefs: ['kw29-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'cluster-robustness',
        order: 50,
        time: '61-75',
        title: 'Cluster + Robustheit',
        work: 'CF Bodyline/Neck; HY Decel-to-Stick + Adduktor; SB Soleus + Assisted Nordic 2x3, Bridge als Regression.',
        dose: 'Kontaktindex 0-1; kein HY-Reaccel, Shield-Hit oder Full Contact.',
        note: 'Kopf/Nacken ohne Neck/Bodyline; Hamstring-Flag ohne Nordic.',
        exposureTags: ['contact_prep', 'cod_decel', 'neck_trunk', 'reconditioning'],
        libraryRefs: ['kw29-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'tempo-closeout',
        order: 60,
        time: '75-90',
        title: 'Optionales Tempo + Abschluss',
        work: 'Tempo Default aus; maximal 4x40 m @ 65-70 % nur nach Coach-Opt-in. Danach Gehen/Atmung, sRPE und Pain/Issue; Coach ergaenzt Dauer, Speed, Kraft, KI und Tempo.',
        dose: 'Tempo 0/1; zuerst streichen. Abschlussdaten bleiben Pflicht.',
        exposureTags: ['conditioning'],
        libraryRefs: ['kw29-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
      },
    ]),
    materials: ['Huetchen', 'MB', 'Trap Bar/KB/DB', 'Baender', 'Matten', 'Sled optional'],
    safetyNotes: [
      'Kein Max-Sprint, Fly, Max-Lift, Bronco, HY-Reaccel oder Full Contact.',
      'Returner: Speed, COD/Deceleration, Conditioning und Kontakt separat cappen.',
      'Concussion-Verdacht oder Kopf/Nacken/Schwindel/neurologisch: sofort raus, medizinisch abklaeren, keine Rueckkehr am selben Tag.',
    ],
    coachNotes: [
      'Kuerzen: Tempo zuerst, dann Cluster, dann Power; Kraft lieber ein sauberer Satz als Hektik.',
      'Heute keine verpassten Saetze, Sprints oder Conditioning-Dosen nachholen.',
    ],
    libraryRefs: ['kw29-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw30-do-2026-07-23',
    date: '2026-07-23',
    kw: 'KW30',
    title: 'Donnerstag 23. Juli: KW30 Entwicklungsreiz',
    type: 'training',
    summary: 'Kontrollierter Off-Season-Entwicklungsreiz: clusterspezifischer Speed/COD, drei saubere Kraftsaetze und zwei gedeckelte Ball-in-Play-Serien.',
    primarySource: 'plans/offseason_coach_sheets/KW30_thursday_training_compact_2026-07-23.md',
    pdfRefs: [
      pdfRefs.kw30ThursdayDeepPlaybook,
      pdfRefs.kw30ThursdayTrainingCompact,
      pdfRefs.kw30ThursdayCheckIn,
    ],
    goals: [
      'A-Skip festigen und Low Dribble entwickeln',
      'Speed und geschlossenes COD clusterspezifisch steigern',
      'Kraft auf drei saubere Arbeitssaetze @ RPE 7 entwickeln',
      'zwei kontrollierte Ball-in-Play-Serien absolvieren',
    ],
    timeline: sessionBlocks('kw30-do-2026-07-23', [
      {
        slug: 'check-in',
        order: 10,
        time: '0-5',
        title: 'Check-in',
        work: 'Readiness, Muskelkater, Schmerz, Life Load, Reaktion auf die letzte Einheit und Returner-Caps; Fly, COD, Kraft und Conditioning pro Spieler entscheiden.',
        dose: 'Gruen/Gelb/Rot; Speed/COD, Kraft, Conditioning und Kontakt separat steuern.',
        note: 'Kopf/Nacken/Schwindel/neurologisch = sofort raus und medizinisch abklaeren.',
        libraryRefs: ['kw30-thursday-active-pack', 'variants-abcd'],
      },
      {
        slug: 'ramp-mobility',
        order: 20,
        time: '5-14',
        title: 'RAMP / Mobility',
        work: 'Lauf, Backpedal und Shuffle je 15 m; Hip Switch 4/Seite, Adductor Rockback 5/Seite, Knee-to-Wall 6/Seite, Squat-to-Stand 3, Open Book 4/Seite, Glute Bridge 8.',
        dose: 'RPE 2-3; Laufbild und Gewebereaktion beobachten.',
        exposureTags: ['mobility'],
        libraryRefs: ['kw30-thursday-active-pack', 'exercise-mapping-offseason'],
      },
      {
        slug: 'track-cod-prep',
        order: 30,
        time: '14-22',
        title: 'Track + COD Prep',
        work: 'A-March 1x10 m, A-Skip 1x10 m, Low Dribble 2x10 m, Pogo 1x10, Snap-down 2x2, Walk-in 45-Grad-Plant 1x2/Seite.',
        dose: 'Technik vorbereiten, nicht ermuenden; Plant geplant und kontrolliert.',
        exposureTags: ['mobility', 'cod_decel'],
        libraryRefs: ['kw30-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'speed-cod',
        order: 40,
        time: '22-35',
        title: 'Speed / COD',
        work: 'CF 3x10 + 2x20 m; HY 2x10 + 2x20 m plus geschlossenes 5-5-5 2x1/Seite; SB 2x10 + 1x30 m plus 2x Build 20/Fly 10 m.',
        dose: 'CF 70 m, HY 60 m plus COD, SB 110 m; Fly ca. 90-92 %, nie maximal.',
        note: 'Gelb ohne Fly/Reaccel und mit 30-50 % weniger Dosis. Volle Pausen.',
        exposureTags: ['speed', 'acceleration', 'cod_decel'],
        libraryRefs: ['kw30-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'power',
        order: 50,
        time: '35-43',
        title: 'Power',
        work: 'Broad Jump + Stick 3x2; MB Rotational Scoop 3x3/Seite bei bekannter Technik, sonst Chest/Punch Pass 3x3.',
        dose: 'Sechs Sprungkontakte, hohe Absicht, sichere Landung; keine Weitenjagd.',
        exposureTags: ['power'],
        libraryRefs: ['kw30-thursday-active-pack', 'exercise-mapping-offseason'],
      },
      {
        slug: 'strength-pods',
        order: 60,
        time: '43-69',
        title: 'Kraft-Pods',
        work: 'A Hinge Vorbereitung + 3x4 @ RPE 7; B Press 3x5-6 + Row 3x6-8; C RFESS/Split Squat 3x5/Seite + Carry 2x20 m.',
        dose: 'Drei saubere Hauptlift-Arbeitssaetze; kein Grind. A+ vierter Satz nur individuell bei kleiner stabiler Gruppe.',
        note: 'Ab 15 Spielern Pod B/C zwei Saetze; Pod A nur bei sauberem Lane-Durchlauf drei Saetze.',
        exposureTags: ['lower_strength', 'upper_strength'],
        libraryRefs: ['kw30-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'cluster-robustness',
        order: 70,
        time: '69-79',
        title: 'Cluster + Robustheit',
        work: 'CF Sled March + Neck; HY Copenhagen/Squeeze + Schulter/Scap; SB Assisted Nordic + Soleus.',
        dose: 'CF Sled 3x10 m; HY 2x15-20 s/Seite + 2x10; SB Nordic 2x4 + Soleus 2x20 s/Seite.',
        note: 'Kontaktindex 0-1; kein Shield-Hit, Live-Tackle oder Full Contact.',
        exposureTags: ['contact_prep', 'neck_trunk', 'reconditioning'],
        libraryRefs: ['kw30-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'conditioning-closeout',
        order: 80,
        time: '79-90',
        title: 'Ball-in-Play + Abschluss',
        work: '2 Serien: 4x20 s Arbeit / 20 s Float, 2 min Serienpause; danach direkt sRPE + Pain/Issue, Coach ergaenzt Dauer, Speed/COD, Kraft, Conditioning und KI.',
        dose: 'Zwei Serien sind die Obergrenze; keine dritte Serie. Gelb ohne Team-Conditioning.',
        note: 'Bei Zeitdruck zuerst die zweite Serie streichen; Technik bleibt erkennbar.',
        exposureTags: ['conditioning'],
        libraryRefs: ['kw30-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
      },
    ]),
    materials: ['Huetchen', 'MB', 'Trap Bar/KB/DB', 'Baender', 'Matten', 'Sleds', 'Carry-Flaeche'],
    safetyNotes: [
      'Kein Max-Sprint, Timing-Rennen, Max-Lift, Bronco, reaktiver harter Cut oder Full Contact.',
      'Fly nur fuer gruene, technisch stabile und symptomfreie Speed/Space Backs.',
      'Returner: Speed, COD/Deceleration, Conditioning und Kontakt separat cappen.',
      'Concussion-Verdacht oder Kopf/Nacken/Schwindel/neurologisch: sofort raus, medizinisch abklaeren, keine Rueckkehr am selben Tag; OnField erteilt keine Freigabe.',
    ],
    coachNotes: [
      'Kuerzen: zweite Ball-in-Play-Serie, Cluster, Med-Ball, dann Pod B/C.',
      'Speed-/Power-Qualitaet und Abschlussdaten nicht durch hektische Wechsel opfern.',
    ],
    libraryRefs: ['kw30-thursday-active-pack', 'exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw31-di-2026-07-28',
    date: '2026-07-28',
    kw: 'KW31',
    title: 'Dienstag 28. Juli: Session 6A',
    type: 'recheck',
    summary: 'Fortschritt sichtbar machen ohne Testtag, Kraft/Sprint konsolidieren und August vorbereiten. RPE 6-7.',
    primarySource: 'plans/offseason_coach_sheets/kw28_31_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw28To31Cards, pdfRefs.exerciseMapping, pdfRefs.preAugustOverview],
    goals: ['optional Mini-Recheck', 'Kraft/Sprint konsolidieren', 'August-Verfuegbarkeit klaeren'],
    timeline: sessionBlocks('kw31-di-2026-07-28', [
      {
        slug: 'checkin-prep-mini-recheck',
        order: 10,
        time: '0-30',
        title: 'Check-in + Prep + Mini-Recheck',
        work: 'Ampel und August-Verfuegbarkeit, RAMP, Landing, Neck/Shoulder, optional Broad Jump + 20-30 m nur frisch.',
        exposureTags: ['mobility', 'power', 'speed'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'power-strength-pods',
        order: 20,
        time: '30-62',
        title: 'Power + Kraft Pods',
        work: 'MB Throw, Hauptlift, Push/Pull, Unilateral + Carry.',
        exposureTags: ['power', 'lower_strength', 'upper_strength'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'microdose-conditioning-august-rules',
        order: 30,
        time: '62-90',
        title: 'Microdose + Conditioning + August-Regeln',
        work: 'Nordic/Copenhagen/Calf, Ball-in-Play oder Tempo, No-Gos klaeren.',
        exposureTags: ['neck_trunk', 'conditioning'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
    ]),
    materials: ['MB', 'Trap Bar/DB', 'Baender', 'Tempo-Flaeche'],
    safetyNotes: ['Mini-Recheck streichen, wenn Anwesenheit unregelmaessig oder Gruppe nicht frisch ist.'],
    coachNotes: ['Fortschritt zeigen, aber keinen Testabend daraus machen.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
  {
    id: 'kw31-do-2026-07-30',
    date: '2026-07-30',
    kw: 'KW31',
    title: 'Donnerstag 30. Juli: Session 6B',
    type: 'transition',
    summary: 'Sauberer Abschluss vor Abreise, bekannte Uebungen festigen, August-Uebergang vorbereiten. RPE 5-6.',
    primarySource: 'plans/offseason_coach_sheets/kw28_31_one_page_field_cards.md',
    pdfRefs: [pdfRefs.kw28To31Cards, pdfRefs.preAugustOverview],
    goals: ['Abschluss vor Abreise', 'bekannte Uebungen festigen', 'August-Uebergang vorbereiten'],
    timeline: sessionBlocks('kw31-do-2026-07-30', [
      {
        slug: 'checkin-prep-speed',
        order: 10,
        time: '0-24',
        title: 'Check-in + Prep + Speed',
        work: 'Ampel, offene Returner-/Schmerzinfos, kurze RAMP, 3x20 m smooth fast.',
        exposureTags: ['mobility', 'speed', 'acceleration'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'power-strength-technique',
        order: 20,
        time: '24-58',
        title: 'Power + Krafttechnik',
        work: 'leichte MB Throws, CMJ + Stick, bekannte Hauptmuster 2-3x5.',
        exposureTags: ['power', 'lower_strength', 'upper_strength'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
      {
        slug: 'august-robustness-closeout',
        order: 30,
        time: '58-90',
        title: 'August Prep + Robustheit + Abschluss',
        work: 'Squat/Hinge/Push/Pull/Carry reviewen, simple Laufoptionen, Hamstring/Adductor/Calf/Shoulder/Trunk, No-Gos.',
        exposureTags: ['lower_strength', 'upper_strength', 'neck_trunk', 'conditioning'],
        libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
      },
    ]),
    materials: ['MB', 'DB/KB', 'Baender', 'August-Unterlagen'],
    safetyNotes: ['No-Go: neue komplexe Uebung, harte Kontaktspitze, Max-Sprints unter Ermuedung.'],
    coachNotes: ['August-Notizen und Verfuegbarkeit sichern.'],
    libraryRefs: ['exercise-mapping-offseason', 'variants-abcd'],
  },
]

function toLocalDateKey(date: Date) {
  const year = date.getFullYear()
  const month = `${date.getMonth() + 1}`.padStart(2, '0')
  const day = `${date.getDate()}`.padStart(2, '0')
  return `${year}-${month}-${day}`
}

export function getRelevantSessions(today = new Date()) {
  const todayKey = toLocalDateKey(today)
  const upcomingIndex = sessionDefinitions.findIndex((session) => session.date >= todayKey)

  if (upcomingIndex === -1) {
    return {
      featuredSession: sessionDefinitions[sessionDefinitions.length - 1],
      upcomingSessions: sessionDefinitions.slice(-2),
    }
  }

  return {
    featuredSession: sessionDefinitions[upcomingIndex],
    upcomingSessions: sessionDefinitions.slice(upcomingIndex, upcomingIndex + 2),
  }
}
